# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-17 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of User')),
                ('friends', models.ManyToManyField(null=True, related_name='_user_friends_+', to='accounts.User', verbose_name='Friends')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
